title: okfetch docs
description: API reference for okfetch packages
baseurl: "/okfetch"
theme: just-the-docs
color_scheme: light
search_enabled: true
aux_links:
  Repository: https://github.com/aldotestino/okfetch
